shape_list = [
    {"name": "Triangle!"},
    {"name": "Square!"},
    {"name": "Rectangle!"},
    {"name": "Waterbottle Shape!"},
    {"name": "Chair Shape!"},
    {"name": "Pyramid Shape!"},
    {"name": "Apple Shape!"},
    {"name": "Banana Shape!"},
    {"name": "Campfire Shape!"},
    {"name": "Trapezium!"},
    {"name": "Hexagon!"},
    {"name": "Triangular Prism!"},
    {"name": "Circle!"},
    {"name": "Star Shape!"},
    {"name": "Sphere!"},
    {"name": "Cat Shape!"},
    {"name": "Lip-Stick Shape!"},
    {"name": "LapTop Shape!"},
    {"name": "Shoe Shape!"},
    {"name": "Hand Shape!"},
    {"name": "Mountain Shape!"},
    {"name": "River Shape!"},
]